_target_: src.models.burgers_module.BurgersLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 200
  gamma: 0.9
  # _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  # _partial_: true
  # mode: min
  # factor: 0.1
  # patience: 10

net:
  _target_: src.models.components.models.PINN
  input_dim: 2
  hidden_dim: 20
  output_dim: 1
  n_layers: 8
  activation: lrelu
