_target_: src.data.datasets.PINNDataset

data_dir: ${paths.data_dir}
filename: ${filename}
idx: 0 # index of instance to train
num_data: 1000 # number of data to use

Nu: 100000 # number of collocation data
Ni: 512 # number of initial data
Nb: 512 # number of boundary data
