defaults:
  - _self_
  - paths: default.yaml
  - hydra: default.yaml

# task name, determines output directory path
task_name: create

generator:
  _target_: src.data.create_data.Data_Generator
  target_pde: Burgers_spectral # pde solver
  xlim: [0.0, 1.0] # spatial domain
  tlim: [0.0, 1.0] # temporal domain
  Nx: 2048 # 2^10 = 1024, spatial resolution
  Nt: 512 # 2^9 = 512, temporal resolution
  coefficient: 0.001 # physical property of pde, kinematic viscosity
  data_dir: ${paths.root_dir}/data/ # path to save data
  backend: torch # backend for computing (numpy / torch / jax / ...)

data_params:
  num_data: 1000 # number of data to create
  m: 0 # mean vector
  sigma: 49 # scaling factor
  tau: 7 # inverse length scale of random field
  gamma: 2.5 # regularity of random field
  is_parallel: false # if true, use multiprocessing

filename: ${generator.target_pde}_${generator.Nx}_${generator.Nt}_${generator.coefficient} # name of data file
