# @package _global_
defaults:
  - _self_
  - paths: default.yaml
  - hydra: default.yaml
  - generator: default.yaml

seed: 41

model_name: null
ckpt_dir: ${paths.model_dir}

plot:
  title: Result - ${model_name}
  filename: Result_${model_name}
  result_dir: ${paths.output_dir}

animate:
  interval: 50
  fps: 60
  filename: Result_${model_name}
  result_dir: ${paths.output_dir}
  num_x: 256
  num_t: 128

# task name, determines output directory path
task_name: eval
