defaults:
  - _self_
  - model: dnn.yaml
  - dataset: dnn.yaml
  - paths: default.yaml
  - hydra: default.yaml

result_dir: ${paths.output_dir}/results
filename: Burgers_2048_0.1
seed: 41

ckpt_path: null # saved model path for inference
model_name: ${model._target_}

plot:
  save_img: True
  show_img: False
  title: Result - ${model_name}
  filename: ${model_name}_result
  result_dir: ${result_dir}

animate:
  save_img: False
  interval: 10
  fps: 60
  filename: Result - ${model_name}
  result_dir: ${result_dir}

task_name: "eval"
